[package]
name = "hedral"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.32.3"
float-cmp = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
static_assertions = "1.1.0"
