[package]
name = "hedral"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.32.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
static_assertions = "1.1.0"
approx = "0.5.1"
criterion = "0.3"
